discriminator: product_type
required:
      - product_type
      - product_id

properties:
  product_id:
    type: string
    description: |
      Unique identifier representing a specific product for a given latitude & longitude.
      For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
  description:
    type: string
    description: Description of product.
  display_name:
    type: string
    description: Display name of product.
  capacity:
    type: string
    description: Capacity of product. For example, 4 people.
  image:
    type: string
    description: Image URL representing the product.
  product_type:
    type: string
    description: type of product.
  labels:
    type: object
    $ref: '../definitions/ToyLabel.yaml'

